http:
  port: 8426

tcp:
  port: 8427

#用户配置d
user:
  database:
    type: sqlite
    dsn: ./data/database/user.db
  auth:
    enable: true
    type: memory
    redis:
      address: 127.0.0.1:6379
      password: ''
      db: 0
    super:
      - 123456789

#中间件
middle:
  #推送失败重试次数
  retry: 0

  #违禁词
  forbidden:
    words:
      - 违禁词1

  #消息队列
  queue:
    limit: 10
    cap: 20

  #日志
  log:
    enable: true


sms:
  aliyun:
    secretID: ''
    secretKey: ''
    signName: ''
    regionID: ''

webhook:
  - test1:
      url: 'https://www.example.com'
      body: {"title": "{title}", "content": "{content}"}
      timeout: 10s

