
http:
  port: 8426

tcp:
  port: 8427

# token 的存储方式,内存或者redis
token:
  type: redis # memory 或者 redis
  address: 127.0.0.1:6379
  password: ''
  db: 0
  super: 123456789 #免验证token

sms:
  aliyun:
    secretID: ''
    secretKey: ''
    signName: ''
    regionID: ''

input:
  #违禁词
  forbidden:
    - 共产党
    - 傻


plugins:
  - prefix: 'injoy'